### ISSUE TITLE
Create a blogs.jakarta.ee tab (similar to http://microprofile.io/blog or https://blogs.eclipse.org/)

### ISSUE THREAD

**Issue by ThabangMash** [jakartaee/jakartaee.github.io#105]
Requirement:
Create a combination blog platform and blog aggregator, so that community members can:
* write and publish blog/articles directly on the jakarta.ee website, i.e. post content is hosted on jakarta.ee 
* share blogs/articles published on their own/3rd party blogs, i.e. blog post is a redirect to another existing blog URL (NOT hosted on jakarta.ee)

How-to instructions should be provided to new authors/content contributors, similar to https://github.com/microprofile/wpsite.

Implementation examples are here:
* https://microprofile.io/blog/
* https://blogs.eclipse.org/

Requested URL for the blog: blogs.jakarta.ee

**Comment by chrisguindon** [comment]
I am closing this issue because we've created a new git repository to host this new blogging website.

The project is currently a work in progress but feedback and pull-requests are more than welcome:
https://github.com/jakartaee/jakartablogs.ee

I will be opening new issues on https://github.com/jakartaee/jakartablogs.ee/issues today to track the reaming tasks for this project
